### ISSUE TITLE
프로그램 실행 시 disk usage 퍼센트 표기 에러

### ISSUE THREAD

**Issue by OZestina** [JaeJunday/42DiskUsage#1]
clear_cache.sh 파일 내 하기 코드로 실제 사용중인 disk usage가 아닌 df -h의 마지막 줄의 내용을 표시하게 됩니다

`# df -h 명령어 실행 및 마지막 줄 추출'
`df_output=$(df -h | tail -n 1)`

유저이름($USER)을 기반으로 수정하면 좋을 것 같습니다.

**Comment by JaeJunday** [comment]
맥에서 df -h의 순서가 꼬이는 상황을 확인했습니다. 유저기반 풀리퀘스트 머지했습니다.
